version: '3.8'

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    logging: *logging
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

    networks:
      - back-tier
    restart: always

  loki:
    depends_on:
      - promtail
    image: grafana/loki:latest
    volumes:
      - ./loki/:/etc/loki/
    ports:
      - "3100:3100"
    command: '-config.file=/etc/loki/loki.yaml'
    logging: *logging
    networks:
      - back-tier
    restart: always

  promtail:
    image: grafana/promtail:latest
    volumes:
      - .log:/var/log
      - ./logs/observability.log:/opt/observability.log
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml
    command: '-config.file=/etc/promtail/promtail.yaml'
    logging: *logging
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    logging: *logging
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
