global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.29.64.1:8080']